### ISSUE TITLE
Some command lines in the README are not working

### ISSUE THREAD

**Issue by stonexjr** [bytedeco/javacpp#269]
For example:
```bash
$ java  -cp javacpp.jar NativeLibrary
```
simply throws error
`Error: Could not find or load main class NativeLibrary`
Need to add current directory to the classpath like:
```bash
$ java  -cp javacpp.jar:. NativeLibrary
```

**Comment by saudet** [comment]
No, it works just fine because "." is in the class path already, see #192. In any case, we can't put `java  -cp javacpp.jar:. NativeLibrary` either because it doesn't work on Windows, we need to use a semi-colon on that platform. Anyway, I'll mark this as a duplicate of #192. Let's continue the discussion there! Thanks
