### ISSUE TITLE
how to close sess in muti thread env

### ISSUE THREAD

**Issue by zhengdi1992** [bytedeco/javacpp#274]
tensorflow.Session  has load successful from a .pb file.
i need update the session once a day because the model updated.
i want to know how to close the old session safely in the muti thread env..

i has found that.. if the old session has not begin to close, other thread can invoke sess.run successfully; if the old session has close completely, other thread can invoke sess.run with null point exception; but, if the old session has closing, when other thread invoker sess.run will occur the process crash down.. : (

i also have try read and write ReentrantReadWriteLock, but it seems also will crash .
any good advices? thanks

additionly! i use the sess.close()  but i find that a another api named sess.Close()..what the difference between them? only return a status or not?

**Comment by saudet** [comment]
`Pointer.close()` is the same as `Pointer.deallocate()` and that basically calls the native destructor, which probably calls `Session.Close()`, but that is part of the C++ API of TensorFlow. They probably do similar things, but `Session.Close()` may not necessarily deallocate the object.

Anyway, to provide the kind of functionality you need, you'll probably have to create your own wrapper class on top of `Session` since `Session.Close()` is not thread safe.
