### ISSUE TITLE
Enums not replaced while templates are instantiated

### ISSUE THREAD

**Issue by jpsacha** [bytedeco/javacpp#50]
Consider example from wrappers for Pylon library. Here is a snippet of the C++ code that defines an `enum` then uses it as a template parameter.

```
enum SequencerModeEnums
{
    SequencerMode_Off,  //!<Disables the sequencer for image acquisition.
    SequencerMode_On   //!<Enables the sequencer for image acquisition.
        
};
...
GenApi::IEnumerationT<SequencerModeEnums > &SequencerMode;
```

To instantiated the template I added to presets:

```java
new Info("GenApi_3_0_Basler_pylon_v5_0::IEnumerationT<Basler_UsbCameraParams::SequencerModeEnums>").pointerTypes("IEnumerationT_SequencerModeEnums").define()
```

This results in the `enum` converted to set of constant values (as expected), and in creation of a class for instantiated template `IEnumerationT_SequencerModeEnums`. But within the `IEnumerationT_SequencerModeEnums` the enum is still referred to by its original C++ type `SequencerModeEnums`, see last line of the snippet below. This results in the compilation error of the Java wrapper.

```java
/** enum Basler_UsbCameraParams::SequencerModeEnums */
public static final int
    /**Disables the sequencer for image acquisition. */
    SequencerMode_Off = 0,
    /**Enables the sequencer for image acquisition. */
    SequencerMode_On = 1;

...
@Name("GenApi_3_0_Basler_pylon_v5_0::IEnumerationT<Basler_UsbCameraParams::SequencerModeEnums>") 
public static class IEnumerationT_SequencerModeEnums extends IEnumeration {
...
  public native void SetValue(@ByVal SequencerModeEnums Value, @Cast("bool") boolean Verify/*=true*/);
```

Complete code illustrating the issue is at commit [f35d4c48](https://github.com/jpsacha/javacpp-presets/commit/f35d4c48ae034dcd7a36eb09514938ada2918825).

**Comment by saudet** [comment]
If we include "pylon/usb/_BaslerUsbCameraParams.h" before "GenApi/IEnumerationT.h", that should fix this issue.

BTW, this is a normal Java source file. We don't need to repeat 200 times
 ```java
.put(new Info("GenApi_3_0_Basler_pylon_v5_0::IEnumerationT<Basler_UsbCameraParams::xxx").pointerTypes("IEnumerationT_xxx").define())
```
Just use a `for` loop for that. :)

**Comment by jpsacha** [comment]
Thanks for the hint. It was not obvious that presets should have imposts in reversed order they are included in C++ code.

**Comment by saudet** [comment]
It's not in the reversed order, it's just that JavaCPP creates instances of a template at its point of definition. When we use templates in C++, that's not what happens. They get instantiated randomly somewhere in the source files. But randomly instantiating them in the Java interface doesn't make sense, because we lose the relationship with the documentation comments and from which files they were parsed. IMO, it makes more sense to instantiate them right away after parsing them. But that entails some trade-offs, as you've discovered. Maybe we can fix some of those things by parsing a second time like the compiler for Java itself does, but do we really need it? I don't know.
